### ISSUE TITLE
Add Ghostly Water

### ISSUE THREAD

**Issue by NotActuallyTerry** [LoveTropics/LTExtras#34]
A barrier-like block which renders like water, but players are able to walk right through it. Useful for making underwater displays (eg. seagrass)

**Comment by Gegy** [comment]
Will also need some additional ✨ fun ✨ to work out how this should interact with waterlogged blocks

**Comment by Gegy** [comment]
'Fish Eye' effect has been added instead to create the desired effect 🙂
