### ISSUE TITLE
Curtains

### ISSUE THREAD

**Issue by DinnerBeef** [LoveTropics/LTExtras#35]
Need some black curtains that allow players to walkthrough them but does not allow any light passed. This is for the theater

**Comment by itsbazke** [comment]
I know this is a very old one but I had a spare few minutes. Is it still wanted? And if so, is this dark enough @DinnerBeef? Github only allows 10mb files so quality is not great... its basically light blocking iron bars that you can walk through.  

[curtain_test.webm](https://github.com/LoveTropics/LTExtras/assets/1597740/6b2dafde-1603-4795-8d9e-a4c205d616a8)
