### ISSUE TITLE
Collectibles/cosmetics system foundations

### ISSUE THREAD

**Issue by Gegy** [LoveTropics/LTExtras#36]
We would like the ability to give players collectible items throughout the stream to make playing in the main world more exciting.

These could be obtained, for example:
 * Through playing minigames
 * Completing the scavenger hunt
 * Finding items hidden around the map
 * Being around for certain events (think: Club Penguin style 'tip the iceberg' giving a reward)
 * Crab golf
 * Donating certain amounts
 * Minigame 'achievements' - e.g. win a game, win STT without attacking anyone
 * Being around for a stream segment
 * Being the top donor in a stream segment
 * More! We should ideally expose cosmetics to be granted via commands for maximum flexibility

Some of these collectibles may be unique, as in, you get one of them and have that forever, while others may be limited-use and you have to complete activities to get more.

Collectibles can vary in their function:
 * A cool hat!
 * A mob disguise (become a Tapir by wearing the item!)
 * Snowballs to throw at your friends
 * Emotes/sound effects (e.g. clapping - could get spammy)
 * An item that makes particles when you are wearing it
 * The head of your favourite streamer (for being online during their segment)
 * More! We should design the system to be as flexible as possible to adding new content

Collectibles should be collectible in a few ways:
 * Picking up a a 'fake item' on the ground
 * Through a minigame action behaviour (such that it can be triggered from other behaviours)
 * Granted by command for custom datapack experiences (or manual use)
 * Donation threshold triggers for the specific player
 * More?

To avoid clutter, collectibles should be able to be kept in a Collectible Basket item
 * For 'unique' items, it's essentially an infinite source
 * For others, it's basically a normal container menu

Some things we should keep in mind:
 * It should not be possible to throw 'unique' collectibles on the ground
 * We might want Vanilla items to be collectible, such as a player head - so we should not limit the technical solution
 * We need to be very careful that players don't lose their collectibles (we've been known to trash players' inventories, particularly on server crash)

**Comment by NotActuallyTerry** [comment]
From draft ticket dated 23/AUG:

"""
Should support both disguises and floating pets (no AI, just visual).
Possibly also a colored glow effect for pets.

These should be selectable through an in-game UI, and we may need backend integration.
"""

Perhaps we could incorporate https://github.com/LoveTropics/meta/issues/13 into this system

**Comment by Gegy** [comment]
Implemented in https://github.com/LoveTropics/LTExtras/commit/aab27e70127f7678034ea2bb2d57c3672af5f21b 🎉
